Update a lot of things

diff --git a/build-ctx/Dockerfile b/build-ctx/Dockerfile
--- a/build-ctx/Dockerfile
+++ b/build-ctx/Dockerfile
@@ -1,8 +1,8 @@
 ARG CF_CPUARCH_DEB_DIST
 
-FROM ws-apache-base-${CF_CPUARCH_DEB_DIST}:latest
+ARG CF_APACHE_BASE_VER
 
-ENV CF_WEBROOT_SITE=site-php
+FROM ws-apache-base-${CF_CPUARCH_DEB_DIST}:${CF_APACHE_BASE_VER}
 
 ENV DEBIAN_FRONTEND=noninteractive
 
@@ -10,18 +10,22 @@ ARG CF_PHP_FPM_VERSION="5.6"
 ENV CF_PHP_FPM_VERSION=$CF_PHP_FPM_VERSION
 
 RUN \
+	apt-get update \
+	&& apt-get upgrade -y \
+	&& apt-get dist-upgrade -y \
 	# dotdeb sources
-		apt-get update \
-		&& echo "deb https://packages.sury.org/php/ stretch main" >> /etc/apt/sources.list.d/php.list \
+	&& echo "deb https://packages.sury.org/php/ stretch main" >> /etc/apt/sources.list.d/php.list \
 	# additional dotdeb source keys
-		&& wget -q https://packages.sury.org/php/apt.gpg -O- | apt-key add -
+	&& wget -q https://packages.sury.org/php/apt.gpg -O- | apt-key add - \
+	# update package lists
+	&& apt-get update
 
 RUN \
 	# install packages
 		apt-get update \
 		&& apt-get install -y --no-install-recommends \
 			# mysql/mariadb packages
-				mysql-client \
+				mariadb-client \
 			# php packages
 				php${CF_PHP_FPM_VERSION} \
 				php${CF_PHP_FPM_VERSION}-fpm \
@@ -32,6 +36,7 @@ RUN \
 				php${CF_PHP_FPM_VERSION}-gd \
 				php${CF_PHP_FPM_VERSION}-imagick \
 				php${CF_PHP_FPM_VERSION}-imap \
+				php${CF_PHP_FPM_VERSION}-intl \
 				php${CF_PHP_FPM_VERSION}-json \
 				php${CF_PHP_FPM_VERSION}-mbstring \
 				php${CF_PHP_FPM_VERSION}-mysql \
@@ -45,21 +50,6 @@ RUN \
 				#libapache2-mod-php${CF_PHP_FPM_VERSION} \
 				php-pear \
 				xml-core
-
-RUN \
-	( a2dismod php${CF_PHP_FPM_VERSION} 2>/dev/null || echo -n "" ) \
-	&& a2enconf php${CF_PHP_FPM_VERSION}-fpm \
-	&& phpdismod xdebug
-
-# copy config files
-COPY files/php/ /etc/php/${CF_PHP_FPM_VERSION}/
-COPY files/apache/000-default.conf /etc/apache2/sites-available/
-
-#
-RUN \
-	mkdir ${CF_WEBROOT}/${CF_WEBROOT_SITE} \
-	&& chmod u=rwx,g=rwxs,o= ${CF_WEBROOT}/${CF_WEBROOT_SITE} \
-	&& mv ${CF_WEBROOT}/index.html ${CF_WEBROOT}/${CF_WEBROOT_SITE}/
 
 #
 RUN \
@@ -75,4 +65,61 @@ RUN \
 			/var/lib/apt/lists*
 
 #
-ENV DEBIAN_FRONTEND=newt
+ENV DEBIAN_FRONTEND=dialog
+
+# install latest version of 'composer'
+RUN \
+	export EXPECTED_SIGNATURE="$(wget -q -O - https://composer.github.io/installer.sig)"; \
+	php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
+	|| exit 1; \
+	export ACTUAL_SIGNATURE="$(php -r "echo hash_file('sha384', 'composer-setup.php');")"; \
+	#
+	if [ -z "$EXPECTED_SIGNATURE" ]; then \
+		echo "EXPECTED_SIGNATURE empty !" >/dev/stderr; \
+		exit 1; \
+	fi; \
+	if [ -z "$ACTUAL_SIGNATURE" ]; then \
+		echo "ACTUAL_SIGNATURE empty !" >/dev/stderr; \
+		exit 1; \
+	fi; \
+	if [ "$EXPECTED_SIGNATURE" != "$ACTUAL_SIGNATURE" ]; then \
+		echo 'ERROR: Invalid installer signature' >/dev/stderr; \
+		exit 1; \
+	fi; \
+	#
+	php composer-setup.php --quiet \
+	&& rm composer-setup.php \
+	&& chmod a+x composer.phar \
+	&& mv composer.phar /usr/local/bin/composer \
+	|| exit 1; \
+	if [ ! -f /usr/share/doc/composer/copyright ]; then \
+		mkdir -p /usr/share/doc/composer; \
+		touch /usr/share/doc/composer/copyright; \
+	fi
+
+RUN \
+	( a2dismod php${CF_PHP_FPM_VERSION} 2>/dev/null || echo -n "" ) \
+	&& a2enconf php${CF_PHP_FPM_VERSION}-fpm \
+	&& phpdismod xdebug
+
+# copy config files
+COPY files/php/ /etc/php/${CF_PHP_FPM_VERSION}/
+COPY files/apache/* /etc/apache2/sites-available/
+
+RUN \
+	chmod 644 /etc/apache2/sites-available/* \
+	&& chown root:root /etc/apache2/sites-available/* \
+	|| exit 1; \
+	test -d /root/apache-defaults || mkdir /root/apache-defaults; \
+	cp /etc/apache2/sites-available/* /root/apache-defaults/
+
+#
+RUN \
+	mv ${CF_WEBROOT}/${CF_WEBROOT_SITE}/index.html ${CF_WEBROOT}/
+
+ENV CF_WEBROOT_SITE=site-php
+
+RUN \
+	mkdir ${CF_WEBROOT}/${CF_WEBROOT_SITE} \
+	&& chmod u=rwx,g=rwxs,o= ${CF_WEBROOT}/${CF_WEBROOT_SITE} \
+	&& mv ${CF_WEBROOT}/index.html ${CF_WEBROOT}/${CF_WEBROOT_SITE}/
